version: 1.3.{build}
pull_requests:
  do_not_increment_build_number: true
image: Ubuntu2004
configuration: Release
only_commits:
  files:
    - MassTransit/CloudEventify.MassTransit/**/*
    - Rebus/CloudEventify.Rebus/**/*
    - appveyor.yml
dotnet_csproj:
  patch: true
  file: '**\*.csproj'
  version: '{version}'
  package_version: '{version}'
  assembly_version: '{version}'
  file_version: '{version}'
  informational_version: '{version}'
build:
  publish_nuget: true
  verbosity: minimal
before_test:
  - docker login -u mriezebosch -p $DOCKER_TOKEN
  - sudo wget -q https://raw.githubusercontent.com/dapr/cli/master/install/install.sh -O - | /bin/bash
  - dapr init --slim
after_test:
  - dotnet tool restore && cd MassTransit.CloudEvents.Tests && dotnet stryker -r "['cleartext']"
test_script:
  - dotnet test --collect:"XPlat Code Coverage"
environment:
  DOCKER_TOKEN:
    secure: Dj3j/X71ZSCnXP24pR/1fmGLBKUYFOeN7R9s+QioevmuSGjGzAGq19hIws1w4Csa
for:
  -
    branches:
      only:
        - main
        - stryker
    environment:
      CODECOV_TOKEN: cdb952b9-902f-4d17-82d7-97d9bfea5e14
      STRYKER_DASHBOARD_API_KEY:
        secure: hjq8RYRkP5jADqnQGO67HK3reNedik0E/M7x67bvWfOmnljS9kIiqiAgvCbn4xL6
    after_test:
      - bash <(curl -s https://codecov.io/bash)
      - dotnet tool restore && cd MassTransit/CloudEventify.MassTransit.Tests && dotnet dotnet-stryker -p 'CloudEventify.MassTransit.csproj' --reporter dashboard --dashboard-api-key $STRYKER_DASHBOARD_API_KEY -c 4
    deploy:
      - provider: NuGet
        api_key:
          secure: 6sPnG9susETMj+SCJB7ESTUOoqhVZ6OAO1W+Qb3Y0h+qjCOo5qnbev8l5ISg32hr
        on:
          branch: main